rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
app_data_path: /srv/bililive/.appdata
read_only_tool_folder: /opt/bililive/tools
feature:
  use_native_flv_parser: false
live_rooms:

# 通知服务配置
notify:
  telegram:
    # 是否开启Telegram通知
    enable: false
    # 是否启用声音通知
    withNotification: true
    # Telegram机器人Token
    botToken: ""
    # Telegram聊天ID
    chatID: ""
  email:
    # 是否开启Email通知
    enable: false
    # SMTP服务器地址 (例如: smtp.gmail.com, smtp.qq.com等)
    smtpHost: "smtp.qq.com"
    # SMTP服务器端口 (常用端口: 25, 465, 587)
    smtpPort: 465
    # 发送者邮箱地址
    senderEmail: ""
    # 发送者邮箱授权码或应用专用密码
    senderPassword: ""
    # 接收者邮箱地址 
    recipientEmail: ""